name: json_to_dart
description: "A new Flutter project."
 
 
publish_to: 'none'  
  
 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_ast: ^1.0.6
  dart_style: ^3.0.0
  provider: ^6.1.2
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

   
  flutter_lints: ^4.0.0

 
 

 
flutter:

  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
